GNB 컴포넌트 작성
PROJECT-BLOB/front-end pull request #75
Opened 2024-05-03 08:59 UTC by Dev-Duke-Seo

## #️⃣연관된 이슈

#73  #74

## 📝작업 내용
- GNB 컴포넌트 작업 후 기본적인 기능을 구현하였고 RootLayout에 적용해두었습니다.
- 내부에 세부기능은 추가작업 예정입니다. 

- [ ] GNB
  - [X] 퍼블리싱
  - [ ] 기능구현
    - [ ] 페이지간 이동
    - [ ] 알림기능
      - [ ] 알림 플로팅메뉴
      - [ ] api 연동

### 예상 기간
- 3일

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
<img width="1770" alt="image" src="https://github.com/PROJECT-BLOB/front-end/assets/127701344/66f81cee-53ff-4d0d-93e7-e5c9f2f2f030">

## 💬리뷰 요구사항(선택)
- 다른 페이지에서 잘 나타나는지 확인해보시고 문제있으면 말씀주세요!

2024-05-03 10:39 UTC, yejiniee requested changes
파일이 잘 분리되어 있어서 읽기 편하네요!! 고생하셨습니다~~

2024-05-03 10:39 UTC, yejiniee commented on app/RootLayout.module.scss
>    flex-direction: column;
@include flex-column; 적용 가능해 보입니다ㅎㅎ

2024-05-03 10:39 UTC, yejiniee commented on components/GlobalNavigationBar/NavigationTab.tsx
> +const NAVIGATION_TABS = [
이 부분 마이페이지에서 베껴가겠습니다ㅋ

2024-05-03 10:39 UTC, yejiniee commented on styles/global-styles/_media-breakpoint.scss
> +@mixin tablet-and-desktop {
새로생겼네요...👍

2024-05-03 10:40 UTC, yejiniee approved these changes

2024-05-03 11:10 UTC, Dev-Duke-Seo commented on styles/global-styles/_media-breakpoint.scss
> +@mixin tablet-and-desktop {
모바일 / 태블릿이상 으로 구분되는 곳에서 사용하시면 됩니다.
- 이외 추가로 필요한 브레이크 포인트는 그냥 미디어쿼리로 작성해주시고
- 반복되는 변형미디어쿼리가 있으면 변수에 등록해서 사용하셔도 좋습니다~!
@yejiniee @chlangus @haeyong9701 @INKmin9

2024-05-03 12:19 UTC, haeyong9701 approved these changes
코드가 전반적으로 깔끔하네요👍
맵이랑 피드페이지도 잘 이동됩니다👍

2024-05-03 12:19 UTC, haeyong9701 commented on components/GlobalNavigationBar/GlobalNavigationBar.module.scss
> +  transition: all 1s ease;
`transition: all 1s ease` 이 부분을 빼도 다른게 없어보이는데 넣은 이유가 있을까요?

2024-05-04 08:45 UTC, chlangus approved these changes
깔끔하게 잘 짜주신것 같아요 bb

2024-05-04 08:46 UTC, merged

2024-05-07 04:59 UTC, Dev-Duke-Seo commented on components/GlobalNavigationBar/GlobalNavigationBar.module.scss
> +  transition: all 1s ease;
오 못보고 지나쳤네요!
애니메이션 테스트한다고 달아둔건데 이때 미쳐 못지웠나봐요
삭제해두었습니다!